language: java
jdk:
- openjdk7
after_success:
- ".buildscript/deploy_snapshot.sh"
env:
  global:
  - secure: p2Soi/L/zKgGlWXFW8Dtoyp7JnKXlWLIcWAoIPznKga+vSgC6gfr2fmHMI8YWOx2IzrrIaSv16yDWLCiWKjcV6WrEzdr/R39y/ABlarXBkNUZ8Ekswc6xqv2lCf8iO0bz+Aky8rIKmBVw43geb+wK0m1Z/KCbN72Xf99P1RJ1TJBDzB+que+4lk1IyZCew7XVnRBjSdPsuYETUS1p0lsX4nFScja0vv0LKFAIvibsutGbuITzWravoBiRXoaxAyB8PtZK+0Ih8o3YkvupXvo4NsXOWJJgYzoW8jPnKcKYGrzuor4LFPCua23kD7H31ngzwBwpTDZLE/QHnvsuLGbTFJLNqdq/Noebvx5QqlZzP0i8U5Ha4ybOdAL1vtATEgE7ZZTVGTgigZZMYuTsuLrrpHbZwOaeZQVcKSpzlpXLT1vy53GPtnP1eg4UjOc6kx1fnSFaWnCvWOln62zE6sadukjr93RibMzKAPPucfVP5iMHubZa7D6Y/HwP6B4jfkUm1PKeHjZgApAeqFw7oMtfkt0Ti/RaQXkyQOnm26B4CKGov2D9VBFTpv2g77HQecimJIMta+Sc8dKgrRbIbBvMHKgT5lSYSgibPjxURf6/i+wxgiXQtTsgyOr1aowTdaxe9Y6ixtPB9Su7BWLcrLC4TqATqLXlRULuAfaE27tRAY=
  - secure: X87b0md6INSaEWg5eXW7ikEjkA5bMvegu1ylXy/mk0QpXDSGEhUS1xvrgl4QIiug+pmQGMTrLQ7/0zAlxSZRZo1bc+DT057LE9q/uG7VJv3T+29m09AUP7Igw62s4ZJ3yyTCwV8VzA1GyZVLKLuR24kuAd75D1k8vLB1JDbq11qwp7GJx3LbFVju+zi+VjwwO9g4pi9TBYa3WwxcBRMIsFHJVGngC/YxaYFswmrNKYS6BV5E/CdHWxY3hkZhN9pMbhxVe4c3jOZBKQIEqC//FRphQ5sWfPOqnBmd6jljjQKkafTLLhaXg//x4IrzXJqHjb+02L+4Bk5tUav1mZE8h8yJ6sdQi94BkZUF0dhifIOtgucAFAUnqzHSL20rTG/YY/Of2bgW7ZA87MVbmAtWBgWnnnjSGMyxKg2M5mqrkQ/r9FvfqmR6amrkqiglrTpyr5NG8bNX/8BVvxbD/SPPFBQTrYZ/gKQwdKZ5BXvisBzbaEum1mkgihkxtmpD0cXRRBzjRfDmcYAjWsEPv/kUZBkaLy74XHJC/zoQjUt4SmI/iF/RxUg0/qYKObfajXirwnGaHcBMI0nJ/SY7FwWmh+FiMm++yHjGrqBZ2StB+NSGKdfQ2E/Q3tnf9RFCRd0IznCsxP0DQrEL4K/RzJdLPAHGJEWIkOMaKhjy70TbfpY=
branches:
  except:
  - gh-pages
